### PR TITLE
Onboard new inter-branch merge flow [Configuration]

### PR DESCRIPTION
**Pull request by f-alizada**
### Context
Onboarding new merge flow based on the github actions

### Changes Made
Added configuration file. The flow was copied from: https://github.com/dotnet/versions/blob/main/Maestro/subscriptions.json. Currently it will not be read or change any behaviour of the merge flow but will be used by the new workflow.

### References
Documentation https://github.com/dotnet/arcade/blob/main/Documentation/Maestro/New-Inter-Branch-Merge-Approach.md
One pager: https://github.com/dotnet/dnceng/blob/main/Documentation/OnePagers/github-action-inter-branch-merge.md

### CODE REVIEW

**Comment by f-alizada** [comment]
@joperezr Could you please check this PR/ is this something that you would like to take into the dotnet/extensions-samples?

**Comment by RussKie** [comment]
@f-alizada could you help us understand how we could check this PR? Is this ready for review? How do we know it is working? 
Thank you

**Comment by joperezr** [comment]
Same here, I don't think we need the release/8.0 -> main any longer, but we want to keep the other one.

**Comment by f-alizada** [comment]
@joperezr Thank you! The pr is updated and the #422 is targeting main branch now :) 

@RussKie Thank you for questions! I have addressed them in: https://github.com/dotnet/extensions/pull/5239#issuecomment-2196562975

Please let me know if that helps

**Review by RussKie — APPROVED** [review]

**Pull request merged**
